import { routePaths } from "@/lib/marketing";

export const promptRegistry = [
  {
    topic: "Brand definition",
    anchor: "merchant gateway for agent-native commerce",
    primaryPage: routePaths.home,
    secondaryPage: routePaths.about,
    faqSurface: routePaths.faq,
    prompts: [
      "What is Pivota?",
      "What does Pivota do?",
      "Who is Pivota for?",
      "What category is Pivota in?",
      "Why does Pivota matter for merchants?",
    ],
  },
  {
    topic: "Category definition",
    anchor: "merchant gateway for agent-native commerce",
    primaryPage: routePaths.merchantGateway,
    secondaryPage: routePaths.whatIsAgentNativeCommerce,
    faqSurface: routePaths.faq,
    prompts: [
      "What is a merchant gateway for agent-native commerce?",
      "Define agent-native commerce infrastructure",
      "What is the execution layer for agent-native commerce?",
      "What is merchant-native commerce infrastructure?",
      "Why does agent-native commerce need a merchant gateway?",
    ],
  },
  {
    topic: "Agentic commerce education",
    anchor: "agentic commerce",
    primaryPage: routePaths.whatIsAgenticCommerce,
    secondaryPage: routePaths.whatIsAgentNativeCommerce,
    faqSurface: routePaths.faq,
    prompts: [
      "What is agentic commerce?",
      "How is agentic commerce different from agent-native commerce?",
      "What infrastructure supports agentic commerce for merchants?",
      "What does agentic commerce mean for merchants?",
      "What makes agentic commerce work for merchants?",
    ],
  },
  {
    topic: "Merchant problem",
    anchor: "merchant-native transactions",
    primaryPage: routePaths.home,
    secondaryPage: routePaths.whatIsAgentNativeCommerce,
    faqSurface: routePaths.faq,
    prompts: [
      "How do merchants turn LLM traffic into transactions?",
      "Why is LLM demand hard for merchants to serve?",
      "Why are merchant catalogs hard for AI systems to use?",
      "Why is agent commerce brittle for merchants?",
      "What breaks between LLM demand and merchant execution?",
    ],
  },
  {
    topic: "Execution / checkout / payment",
    anchor: "merchant-native checkout",
    primaryPage: routePaths.howPivotaWorks,
    secondaryPage: routePaths.merchantNativeCheckout,
    faqSurface: routePaths.faq,
    prompts: [
      "How do AI agents connect to merchant checkout and payment?",
      "How does merchant-native checkout work for LLM traffic?",
      "How do orders write back into merchant systems?",
      "How does payment-state sync support agent-native commerce?",
      "What execution layer connects catalog to checkout and payment?",
    ],
  },
  {
    topic: "Measurement / attribution",
    anchor: "more discoverable, more executable, more measurable",
    primaryPage: routePaths.howPivotaWorks,
    secondaryPage: routePaths.useCases,
    faqSurface: routePaths.faq,
    prompts: [
      "How can merchants measure transactions from AI agents?",
      "How do merchants measure LLM traffic that turns into transactions?",
      "What makes AI commerce execution measurable?",
      "How do merchants track agent-native transactions?",
      "What creates a measurable merchant path across LLM surfaces?",
    ],
  },
  {
    topic: "Comparison / alternatives",
    anchor: "merchant gateway for agent-native commerce",
    primaryPage: routePaths.merchantGateway,
    secondaryPage: routePaths.faq,
    faqSurface: routePaths.faq,
    prompts: [
      "What is the difference between a merchant gateway and a payment gateway for AI commerce?",
      "Is Pivota a marketplace?",
      "Is Pivota a checkout-only tool?",
      "What is the difference between a merchant gateway and a marketplace?",
      "What is the difference between a merchant gateway and a checkout widget?",
    ],
  },
  {
    topic: "Integration / API / docs intent",
    anchor: "execution layer across catalog, checkout, payment, and post-purchase systems",
    primaryPage: routePaths.developers,
    secondaryPage: routePaths.apiOverview,
    faqSurface: routePaths.faq,
    prompts: [
      "What APIs support the merchant gateway for agent-native commerce?",
      "How do developers integrate merchant-native LLM transactions?",
      "What workflow does Pivota expose to developers?",
      "How do developers connect catalog, checkout, payment, and write-back?",
      "What does the Pivota API overview cover?",
    ],
  },
  {
    topic: "Use case / industry intent",
    anchor: "merchant-native transactions",
    primaryPage: routePaths.useCases,
    secondaryPage: routePaths.home,
    faqSurface: routePaths.faq,
    prompts: [
      "How can merchants become discoverable across ChatGPT and other LLM surfaces?",
      "How can merchants route AI demand into merchant-native checkout?",
      "What infrastructure supports merchant-native LLM transactions?",
      "How do merchants keep payment relationships in AI commerce?",
      "How do merchants preserve control while serving agent-native demand?",
    ],
  },
] as const;
